refact(e2e): Use docker infrastructure for end-to-end tests

diff --git a/.github/workflows/enos-run.yml b/.github/workflows/enos-run.yml
--- a/.github/workflows/enos-run.yml
+++ b/.github/workflows/enos-run.yml
@@ -72,10 +72,12 @@ jobs:
       fail-fast: false # don't fail as that can skip required cleanup steps for jobs
       matrix:
         include:
-          - filter: 'e2e_aws builder:crt'
-          - filter: 'e2e_database'
-          - filter: 'e2e_static builder:crt'
-          - filter: 'e2e_static_with_vault builder:crt'
+          # - filter: 'e2e_aws builder:crt'
+          # - filter: 'e2e_database'
+          # - filter: 'e2e_static builder:crt'
+          # - filter: 'e2e_static_with_vault builder:crt'
+          - filter: 'e2e_docker_base builder:crt'
+          - filter: 'e2e_docker_base_with_vault builder:crt'
           # - filter: 'e2e_ui builder:crt' # Don't run UI tests yet. takes too long.
     runs-on: ${{ fromJSON(vars.RUNNER) }}
     env:
@@ -162,12 +164,12 @@ jobs:
         run: |
           wget https://releases.hashicorp.com/vault/1.12.2/vault_1.12.2_linux_amd64.zip -O /tmp/test-deps/vault.zip
       - name: Install Vault CLI
-        if: matrix.filter == 'e2e_static_with_vault builder:crt' || matrix.filter == 'e2e_database' || matrix.filter == 'e2e_ui builder:crt' || matrix.filter == 'e2e_docker builder:crt'
+        if: matrix.filter == 'e2e_static_with_vault builder:crt' || matrix.filter == 'e2e_database' || matrix.filter == 'e2e_ui builder:crt' || matrix.filter == 'e2e_docker_base_with_vault builder:crt'
         run: |
           unzip /tmp/test-deps/vault.zip -d /usr/local/bin
       - name: Add hosts to /etc/hosts
         # This enables the use of `boundary connect` with docker containers
-        if: matrix.filter == 'e2e_docker builder:crt'
+        if: contains(matrix.filter, 'e2e_docker')
         run: |
           sudo echo "127.0.0.1 localhost boundary" | sudo tee -a /etc/hosts
       - name: Download Boundary Linux AMD64 bundle
@@ -181,14 +183,14 @@ jobs:
           unzip ${{steps.download.outputs.download-path}}/*.zip -d enos/support/boundary
           mv ${{steps.download.outputs.download-path}}/*.zip enos/support/boundary.zip
       - name: Download Boundary Linux AMD64 docker image
-        if: matrix.filter == 'e2e_docker builder:crt'
+        if: contains(matrix.filter, 'e2e_docker')
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
         id: download-docker
         with:
           name: ${{ inputs.docker-image-file }}
           path: ./enos/support/downloads
       - name: Rename docker image file
-        if: matrix.filter == 'e2e_docker builder:crt'
+        if: contains(matrix.filter, 'e2e_docker')
         run: |
           mv ${{ steps.download-docker.outputs.download-path }}/*.tar enos/support/boundary_docker_image.tar
       - name: Set up Node.js
@@ -297,28 +299,28 @@ jobs:
         run: |
           env
           find ./enos -name "scenario.tf" -exec cat {} \;
-      - name: Send Slack message if Run and Retry fails (or if something else went wrong)
-        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
-        # steps.run.outcome reports as failure when there is an error in `Run Enos scenario`
-        # failure() captures errors before `Run Enos scenario`
-        # failure() does not capture errors in `Run Enos scenario` due to continue-on-error
-        if: ${{ failure() || (steps.run.outcome == 'failure' && steps.run_retry.outcome == 'failure') }}
-        with:
-          channel-id: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_CHANNEL_ID }}
-          payload: |
-            {
-              "text": ":x: e2e tests failed (${{ matrix.filter }}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Branch:* ${{ github.event.ref }}\n*SHA:* <${{ github.event.head_commit.url }}|${{ github.event.after }}>"
-            }
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_TOKEN }}
-      - name: Send Slack message if Run but Retry passes
-        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
-        if: ${{ steps.run.outcome == 'failure' && steps.run_retry.outcome != 'failure' }}
-        with:
-          channel-id: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_CHANNEL_ID }}
-          payload: |
-            {
-              "text": ":warning: e2e tests passed, but needed retry (${{ matrix.filter }}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Branch:* ${{ github.event.ref }}\n*SHA:* <${{ github.event.head_commit.url }}|${{ github.event.after }}>"
-            }
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_TOKEN }}
+      # - name: Send Slack message if Run and Retry fails (or if something else went wrong)
+      #   uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
+      #   # steps.run.outcome reports as failure when there is an error in `Run Enos scenario`
+      #   # failure() captures errors before `Run Enos scenario`
+      #   # failure() does not capture errors in `Run Enos scenario` due to continue-on-error
+      #   if: ${{ failure() || (steps.run.outcome == 'failure' && steps.run_retry.outcome == 'failure') }}
+      #   with:
+      #     channel-id: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_CHANNEL_ID }}
+      #     payload: |
+      #       {
+      #         "text": ":x: e2e tests failed (${{ matrix.filter }}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Branch:* ${{ github.event.ref }}\n*SHA:* <${{ github.event.head_commit.url }}|${{ github.event.after }}>"
+      #       }
+      #   env:
+      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_TOKEN }}
+      # - name: Send Slack message if Run but Retry passes
+      #   uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
+      #   if: ${{ steps.run.outcome == 'failure' && steps.run_retry.outcome != 'failure' }}
+      #   with:
+      #     channel-id: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_CHANNEL_ID }}
+      #     payload: |
+      #       {
+      #         "text": ":warning: e2e tests passed, but needed retry (${{ matrix.filter }}): ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Branch:* ${{ github.event.ref }}\n*SHA:* <${{ github.event.head_commit.url }}|${{ github.event.after }}>"
+      #       }
+      #   env:
+      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOUNDARY_TEST_BOT_TOKEN }}
